# NOTES
# -----
# Purpose: used to execute commands and set environment variables that should be in place for the entire duration of the login session.
# This includes setting the PATH environment variable, environment variables required for installed software, and running scripts that should only be executed once at the start of a login session.
# If you set an environment variable, it will be set for all subsequent terminal sessions.

# Called by login shells:
# - sudo -i
# - bash -l
# - ssh frida@127.0.0.1 

# UMASK
# -----

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# SOURCE .bashrc
# --------------

if [ -n "${BASH_VERSION}" ]; then # if running bash
    if [ -f "${HOME}/.bashrc" ]; then # include .bashrc if it exists
	    . "${HOME}/.bashrc"
    fi
fi
